local craftTables = {}
craftTables["Microchip (Tier 1)"] = {"Iron Nugget", "Iron Nugget", "Iron Nugget", "Redstone", "Transistor", "Redstone", "Iron Nugget", "Iron Nugget", "Iron Nugget"}
craftTables["Microchip (Tier 2)"] = {"Gold Nugget", "Gold Nugget", "Gold Nugget", "Redstone", "Transistor", "Redstone", "Gold Nugget", "Gold Nugget", "Gold Nugget"}
craftTables["Transistor"] = {"Iron Ingot", "Iron Ingot", "Iron Ingot", "Gold Nugget", "Paper", "Gold Nugget", "", "Redstone", ""}
craftTables["Microchip (Tier 3)"] = {"Diamond Chip", "Diamond Chip", "Diamond Chip", "Redstone", "Transistor", "Redstone", "Diamond Chip", "Diamond Chip", "Diamond Chip"}
craftTables["Cutting Wire"] = {"Stick", "Iron Nugget", "Stick", "", "", "", "", "", ""}
craftTables["Diamond Chip"] = {"Cutting Wire", "Diamond", "", "", "", "", "", "", ""}
craftTables["Iron Nugget"] = {"Iron Ingot", "", "", "", "", "", "", "", ""}
craftTables["Iron Ingot"] = {"Block of Iron", "", "", "", "", "", "", "", ""}
craftTables["Gold Nugget"] = {"Gold Ingot", "", "", "", "", "", "", "", ""}
craftTables["Redstone"] = {"Block of Redstone", "", "", "", "", "", "", "", ""}
craftTables["Clock"] = {"", "Gold Ingot", "", "Gold Ingot", "Redstone", "Gold Ingot", "", "Gold Ingot", ""}
craftTables["Control Unit (CU)"] = {"Gold Nugget", "Redstone", "Gold Nugget", "Transistor", "Clock", "Transistor", "Gold Nugget", "Transistor", "Gold Nugget"}
craftTables["Arithmetic Logic Unit (ALU)"] = {"Iron Nugget", "Redstone", "Iron Nugget", "Transistor", "Microchip (Tier 1)", "Transistor", "Iron Nugget", "Transistor", "Iron Nugget"}
craftTables["Central Processing Unit (CPU) (Tier 3)"] = {"Diamond Chip", "Redstone", "Diamond Chip", "Microchip (Tier 3)", "Control Unit (CU)", "Microchip (Tier 3)", "Diamond Chip", "Arithmetic Logic Unit (ALU)", "Diamond Chip"}
craftTables["Component Bus (Tier 2)"] = {"Gold Nugget", "Redstone", "Gold Nugget", "Microchip (Tier 2)", "Control Unit (CU)", "", "Gold Nugget", "Printed Circuit Board (PCB)", "Gold Nugget"}
craftTables["Card Base"] = {"Iron Nugget", "", "", "Iron Nugget", "Printed Circuit Board (PCB)", "", "Iron Nugget", "Gold Nugget", ""}
craftTables["Memory (Tier 2)"] = {"", "", "", "Microchip (Tier 2)", "Iron Nugget", "Microchip (Tier 2)", "", "Printed Circuit Board (PCB)", ""}
craftTables["Graphics Card (Tier 2)"] = {"", "", "", "Microchip (Tier 2)", "Arithmetic Logic Unit (ALU)", "Memory (Tier 2)", "", "Card Base", ""}
craftTables["Accelerated Processing Unit (APU) (Tier 2)"] = {"Diamond Chip", "Microchip (Tier 2)", "Diamond Chip", "Central Processing Unit (CPU) (Tier 3)", "Component Bus (Tier 2)", "Graphics Card (Tier 2)", "Diamond Chip", "Microchip (Tier 2)", "Diamond Chip"}
craftTables["Memory (Tier 3.5)"] = {"", "", "", "Microchip (Tier 3)", "Microchip (Tier 3)", "Microchip (Tier 3)", "Microchip (Tier 2)", "Printed Circuit Board (PCB)", "Microchip (Tier 2)"}
craftTables["Button"] = {"Stone", "", "", "", "", "", "", "", ""}
craftTables["Numeric Keypad"] = {"Button", "Button", "Button", "Button", "Button", "Button", "Button", "Button", "Button"}
craftTables["Arrow Keys"] = {"", "", "", "", "Button", "", "Button", "Button", "Button"}
craftTables["Button Group"] = {"", "", "", "Button", "Button", "Button", "Button", "Button", "Button"}
craftTables["Keyboard"] = {"", "", "", "Button Group", "Button Group", "Button Group", "Button Group", "Arrow Keys", "Numeric Keypad"}
craftTables["Screen (Tier 1)"] = {"Iron Ingot", "Redstone", "Iron Ingot", "Redstone", "Microchip (Tier 1)", "Glass", "Iron Ingot", "Redstone", "Iron Ingot"}
craftTables["Computer Case (Tier 3)"] = {"Diamond", "Microchip (Tier 3)", "Diamond", "Iron Bars", "Chest", "Iron Bars", "Diamond", "Printed Circuit Board (PCB)", "Diamond"}
craftTables["Iron Bars"] = {"", "", "", "Iron Ingot", "Iron Ingot", "Iron Ingot", "Iron Ingot", "Iron Ingot", "Iron Ingot"}
craftTables["Hard Disk Drive (Tier 3) (4MB)"] = {"Microchip (Tier 3)", "Disk Platter", "Diamond", "Printed Circuit Board (PCB)", "Disk Platter", "Piston", "Microchip (Tier 3)", "Disk Platter", "Diamond"}
craftTables["Disk Platter"] = {"", "Iron Nugget", "", "Iron Nugget", "", "Iron Nugget", "", "Iron Nugget", ""}
craftTables["Upgrade Container (Tier 1)"] = {"Iron Ingot", "Microchip (Tier 1)", "Iron Ingot", "Piston", "Chest", "", "Iron Ingot", "Printed Circuit Board (PCB)", "Iron Ingot"}
craftTables["Upgrade Container (Tier 2)"] = {"Iron Ingot", "Microchip (Tier 2)", "Iron Ingot", "Piston", "Chest", "", "Iron Ingot", "Printed Circuit Board (PCB)", "Iron Ingot"}
craftTables["Redstone Torch"] = {"", "Redstone", "", "", "Stick", "", "", "", ""}
craftTables["Upgrade Container (Tier 3)"] = {"Gold Ingot", "Microchip (Tier 2)", "Gold Ingot", "Piston", "Chest", "", "Gold Ingot", "Printed Circuit Board (PCB)", "Gold Ingot"}
craftTables["Eye of Ender"] = {"Ender Pearl", "Blaze Powder", "", "", "", "", "", "", ""}
craftTables["Chunkloader Upgrade"] = {"Gold Ingot", "Glass", "Gold Ingot", "Microchip (Tier 3)", "Eye of Ender", "Microchip (Tier 3)", "Obsidian", "Printed Circuit Board (PCB)", "Obsidian"}
craftTables["Redstone Card (Tier 1)"] = {"", "", "", "Redstone Torch", "Microchip (Tier 1)", "", "", "Card Base", ""}
craftTables["Redstone Card (Tier 2)"] = {"", "", "", "Block of Redstone", "Microchip (Tier 2)", "Ender Pearl", "", "Card Base", ""}
craftTables["Dropper"] = {"Cobblestone", "Cobblestone", "Cobblestone", "Cobblestone", "", "Cobblestone", "Cobblestone", "Redstone", "Cobblestone"}
craftTables["Analyzer"] = {"Redstone Torch", "", "", "Transistor", "Gold Nugget", "", "Printed Circuit Board (PCB)", "Gold Nugget", ""}
craftTables["Inventory Controller Upgrade"] = {"Gold Ingot", "Analyzer", "Gold Ingot", "Dropper", "Microchip (Tier 2)", "Piston", "Gold Ingot", "Printed Circuit Board (PCB)", "Gold Ingot"}
craftTables["Generator Upgrade"] = {"Iron Ingot", "", "Iron Ingot", "Microchip (Tier 1)", "Piston", "Microchip (Tier 1)", "Iron Ingot", "Printed Circuit Board (PCB)", "Iron Ingot"}
craftTables["Interweb"] = {"String", "String", "String", "String", "Ender Pearl", "String", "String", "String", "String"}
craftTables["Internet Card"] = {"", "", "", "Interweb", "Microchip (Tier 2)", "Redstone Torch", "", "Card Base", "Obsidian"}
craftTables["Chamelium"] = {"Gravel", "Redstone", "Gravel", "Redstone", "Charcoal", "Redstone", "Gravel", "Water Bucket", "Gravel"}
craftTables["Wireless Network Card (Tier 2)"] = {"", "", "", "Ender Pearl", "Microchip (Tier 2)", "", "", "Card Base", ""}
craftTables["Capacitor"] = {"Iron Ingot", "Transistor", "Iron Ingot", "Gold Nugget", "Paper", "Gold Nugget", "Iron Ingot", "Printed Circuit Board (PCB)", "Iron Ingot"}
craftTables["Grog"] = {"Water Bucket", "Sugar", "Slimeball", "Fermented Spider Eye", "Bone", "", "", "", ""}
craftTables["Fermented Spider Eye"] = {"Spider Eye", "Mushroom", "", "Sugar", "", "", "", "", ""}
craftTables["Central Processing Unit (CPU) (Tier 1)"] = {"Iron Nugget", "Redstone", "Iron Nugget", "Microchip (Tier 1)", "Control Unit (CU)", "Microchip (Tier 1)", "Iron Nugget", "Arithmetic Logic Unit (ALU)", "Iron Nugget"}
craftTables["Central Processing Unit (CPU) (Tier 2)"] = {"Gold Nugget", "Redstone", "Gold Nugget", "Microchip (Tier 2)", "Control Unit (CU)", "Microchip (Tier 2)", "Gold Nugget", "Arithmetic Logic Unit (ALU)", "Gold Nugget"}
craftTables["Nanomachines"] = {"Chamelium", "Wireless Network Card (Tier 2)", "Chamelium", "Central Processing Unit (CPU) (Tier 2)", "Grog", "Memory (Tier 1)", "Chamelium", "Capacitor", "Chamelium"}
craftTables["Battery Upgrade (Tier 1)"] = {"Iron Nugget", "Gold Nugget", "Iron Nugget", "Iron Bars", "Capacitor", "Iron Bars", "Iron Nugget", "Gold Nugget", "Iron Nugget"}
craftTables["Component Bus (Tier 3)"] = {"Diamond Chip", "Redstone", "Diamond Chip", "Microchip (Tier 3)", "Control Unit (CU)", "", "Diamond Chip", "Printed Circuit Board (PCB)", "Diamond Chip"}
craftTables["Tablet Case (Tier 2)"] = {"Microchip (Tier 2)", "Button", "Gold Ingot", "Component Bus (Tier 3)", "Screen (Tier 2)", "Microchip (Tier 3)", "Microchip (Tier 2)", "Printed Circuit Board (PCB)", "Gold Ingot"}
craftTables["Memory (Tier 1)"] = {"", "", "", "Microchip (Tier 1)", "Iron Nugget", "Microchip (Tier 1)", "", "Printed Circuit Board (PCB)", ""}
craftTables["Graphics Card (Tier 1)"] = {"", "", "", "Microchip (Tier 1)", "Arithmetic Logic Unit (ALU)", "Memory (Tier 1)", "", "Card Base", ""}
craftTables["Component Bus (Tier 1)"] = {"Iron Nugget", "Redstone", "Iron Nugget", "Microchip (Tier 1)", "Control Unit (CU)", "", "Iron Nugget", "Printed Circuit Board (PCB)", "Iron Nugget"}
craftTables["Accelerated Processing Unit (APU) (Tier 1)"] = {"Gold Nugget", "Microchip (Tier 1)", "Gold Nugget", "Central Processing Unit (CPU) (Tier 2)", "Component Bus (Tier 1)", "Graphics Card (Tier 1)", "Gold Nugget", "Microchip (Tier 1)", "Gold Nugget"}
craftTables["Memory (Tier 1.5)"] = {"", "", "", "Microchip (Tier 1)", "Microchip (Tier 2)", "Microchip (Tier 1)", "", "Printed Circuit Board (PCB)", ""}
craftTables["Memory (Tier 2.5)"] = {"", "", "", "Microchip (Tier 2)", "Microchip (Tier 3)", "Microchip (Tier 2)", "", "Printed Circuit Board (PCB)", ""}
craftTables["Hard Disk Drive (Tier 1) (1MB)"] = {"Microchip (Tier 1)", "Disk Platter", "Iron Ingot", "Printed Circuit Board (PCB)", "Disk Platter", "Piston", "Microchip (Tier 1)", "Disk Platter", "Iron Ingot"}
craftTables["Hard Disk Drive (Tier 2) (2MB)"] = {"Microchip (Tier 2)", "Disk Platter", "Gold Ingot", "Printed Circuit Board (PCB)", "Disk Platter", "Piston", "Microchip (Tier 2)", "Disk Platter", "Gold Ingot"}
craftTables["Battery Upgrade (Tier 2)"] = {"Iron Nugget", "Capacitor", "Iron Nugget", "Iron Bars", "Gold Nugget", "Iron Bars", "Iron Nugget", "Capacitor", "Iron Nugget"}
craftTables["Battery Upgrade (Tier 3)"] = {"Iron Nugget", "Capacitor", "Iron Nugget", "Capacitor", "Diamond Chip", "Capacitor", "Iron Nugget", "Capacitor", "Iron Nugget"}
craftTables["Microcontroller Case (Tier 2)"] = {"Gold Nugget", "Microchip (Tier 3)", "Gold Nugget", "Block of Redstone", "Chest", "Block of Redstone", "Gold Nugget", "Printed Circuit Board (PCB)", "Gold Nugget"}
craftTables["Drone Case (Tier 2)"] = {"End Stone", "Compass", "End Stone", "Microchip (Tier 2)", "Microcontroller Case (Tier 2)", "Microchip (Tier 2)", "End Stone", "Component Bus (Tier 3)", "End Stone"}
craftTables["Compass"] = {"", "Iron Ingot", "", "Iron Ingot", "Redstone", "Iron Ingot", "", "Iron Ingot", ""}
craftTables["Disk Drive"] = {"Iron Ingot", "Microchip (Tier 1)", "Iron Ingot", "Piston", "Stick", "", "Iron Ingot", "Printed Circuit Board (PCB)", "Iron Ingot"}
return craftTables
